import "styles/globals.css"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { twMerge } from "tailwind-merge"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, "bg-neutral-800")}>{children}</body>
    </html>
  )
}
